#%RAML 1.0 Trait
headers:
  correlationId:
    type: string
    required: true
    minLength: 1
    maxLength: 50
    example: "adfs-kfjla-lkfj"
  appName:
    type: string
    required: true
    minLength: 1
    maxLength: 50
    example: "hdfc-communication-sms-sys-api-v1"
