name: MulSoft Build & Deploy

on:
  push:
    branches:
    - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: write
      pull-requests: write
      contents: read
    outputs:
      appversion: ${{ steps.fetch_version.outputs.version}}  

    steps:
      - uses: actions/checkout@v2
      - uses: s4u/maven-settings-action@v2.7.0
        with:
            servers: '[{"id":"${{ secrets.ANYPOINT_ID }}", "username":"${{ secrets.ANYPOINT_USERNAME }}", "password":"${{ secrets.ANYPOINT_PASSWORD }}"}]'

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: checkout dependency repo
        uses: actions/checkout@v2
        with:
          repository: Unacores/hdfc-logging-errorhandler-util
          token: ${{ secrets.PAT }}
          path: main
      
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          # repositories: '[{ "id": "some-repository", "url": "http://some.repository.url" }]'
          # plugin_repositories: '[{ "id": "some-plugin-repository", "url": "http://some.plugin.repository.url" }]'
          servers: '[{"id":"housing-development", "username":"satya206", "password":"Satya206"}]'

      - name: Build dependency pom
        working-directory: ./main/
       # run: mvn -B package --file pom.xml
        run: mvn clean install
        
      - name: Build MuleSoft Application
        run: mvn -B package --file pom.xml

      - name: Fetch application version
        run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "::set-output name=version::$VERSION"
        id: fetch_version  


      - name: Deploy SMS Communication SYS API on UAT
        env:
          USERNAME: ${{ secrets.MULESOFT_USERNAME }}
          PASSWORD: ${{ secrets.MULESOFT_PASSWORD }}
          KEY: ${{ secrets.MULE_KEY }}
        run: |
          artifactName=./target/hdfc-communication-sms-sys-api-v1-${{ steps.fetch_version.outputs.version }}-mule-application.jar
          mvn -U deploy -DmuleDeploy \
          -Dmule.artifact="$artifactName" \
          -Danypoint.environment="MuleSoft-DEV" \
          -Danypoint.target="Cluster-UAT" \
          -Danypoint.username="$USERNAME" \
          -Danypoint.password="$PASSWORD" \
          -Danypoint.key="$KEY" \
          -Danypoint.env="dev" \
          -DskipTests
